// dm/src/App.tsx
import './App.css'
import { io } from "socket.io-client";

function App() {
  const URL = "http://localhost:3000";
  const socket = io(URL, { autoConnect: false });
  let usernameAlreadySelected:boolean = false;

  socket.onAny((event, ...args) => {
    console.log(event, args);
  });

  const onUsernameSelection = (event:any) => {
    usernameAlreadySelected = true;
    const username:string = event.target.value;
    socket.auth = { username };
    socket.connect();
  }

  socket.on("connect_error", (err) => {
    if (err.message === "invalid username") {
      usernameAlreadySelected = false;
    }
  });

  return (
    <div className="App">
      <div className="select-username">
        <form onSubmit={onUsernameSelection}>
          <input placeholder='Your name'></input>
          <button>Send</button>
        </form>
      </div>
    </div>
  )
}

export default App

// PP_chat/private-messaging/src/App.vue
<template>
  <div id="app">
    <select-username
      v-if="!usernameAlreadySelected"
      @input="onUsernameSelection"
    />
    <chat v-else />
  </div>
</template>

<script>
import SelectUsername from "./components/SelectUsername";
import Chat from "./components/Chat";
import socket from "./socket";

export default {
  name: "App",
  components: {
    Chat,
    SelectUsername,
  },
  data() {
    return {
      usernameAlreadySelected: false,
    };
  },
  methods: {
    onUsernameSelection(username) {
      this.usernameAlreadySelected = true;
      socket.auth = { username };
      socket.connect(
        (val) => {
          console.log("connected", val);
        }
      );
    },
  },
  created() {
    socket.on("connect_error", (err) => {
      if (err.message === "invalid username") {
        this.usernameAlreadySelected = false;
      }
    });
  },
  destroyed() {
    socket.off("connect_error");
  },
};
</script>

<style>
body {
  margin: 0;
}

@font-face {
  font-family: Lato;
  src: url("/fonts/Lato-Regular.ttf");
}

#app {
  font-family: Lato, Arial, sans-serif;
  font-size: 14px;
}
</style>
